version: "3.8"

services: 
  app:

    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"    
    volumes:
      - .:/rails_docker_app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: "3e53962edea935c4b4d3a3678b1703f51c2fd79c9410d9aaebe039aca3548786f3b2973310ecaec593b549f348ca5663806fdbe77aa6feee364aa3d9f636c359"

      DB_USERNAME: root
      DB_PASSWORD: 123456789
      DB_HOST: db
  db:
    image: mysql:5.5
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/rails_docker_app
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: intern_development

volumes:
  db_data:
    driver: local
  bundle:
    driver: local
