

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 'root' } %>
  password: <%= ENV.fetch("DB_PASS") { '123456789' } %>
  socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV.fetch("DB_HOST") { 'mysql.railway.internal' } %>
development:
  <<: *default
  database: intern_development 

test:
  <<: *default
  database: intern_test

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV["MYSQLHOST"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
  port: <%= ENV["MYSQLPORT"] %>
