

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USER")%>
  password: <%= ENV.fetch("DB_PASS")%>
  database: intern_development 

test:
  <<: *default
  database: intern_test

production:
  <<: *default
  url: <%= ENV["MYSQL_URL"] %>
  host: <%= ENV["MYSQLHOST"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
  port: <%= ENV["MYSQLPORT"] %>
